### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by MaximusXYZ** [Trollicus/AutoJoiner#3]
I tried RestSharp even this and other stuff. My token grabber is working fine but it just doesn't wanna work for me

**Comment by Trollicus** [comment]
It'll be fixed as soon as possible. If you found solution and works please make a pull request!

**Comment by MaximusXYZ** [comment]
Hello, I have found a solution.

`HttpClient Client = new HttpClient();
Client.DefaultRequestHeaders.Add("User-Agent", "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) discord/0.0.305 Chrome/69.0.3497.128 Electron/4.0.8 Safari/537.36");
Client.DefaultRequestHeaders.Add("authorization", Token.Replace("\n", "").Replace("\r", ""));
await Client.PostAsync("https://discordapp.com/api/v6/invite/" + Invite, null);`
